### ISSUE TITLE
:export support

### ISSUE THREAD

**Issue by sobolevn** [pascalduez/stylelint-config-css-modules#4] opened 2018-05-13 08:22 UTC
Hi! Thanks for putting all this stuff together. It really helps.

I have a question about handling an `:export` case. That's what I mean:

```
$some-var: blue; // scss syntax

:export {
   global-var: $some-var;
}
```

What I get is: `[stylelint] Unexpected unknown property "global-var" (property-no-unknown)`
How to handle this situation? 

Thanks!

**Comment by pascalduez** [comment] 2018-05-13 09:05
Hi,

I think this have to be handled on your side with the `property-no-unknown` rule. Make your own whitelist.
Not sure whether there's some sort of wildcard enabled config for I could add here.

Dupe of #3

**Comment by pascalduez** [comment] 2018-05-13 09:10
Another solution would be to disable locally with comments.

**Closed as completed** 2018-05-13 09:19 UTC

**Comment by pascalduez** [comment] 2019-11-04 15:36
As of `stylelint-config-css-modules@2.0.0` this is supported without any additional tweak.
